### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by mozo78** [netbospl/dolphin-git#1]
Hello,
Currently there's a problem compilng. It gives me:

https://pastebin.com/JPAuMiwS

**Comment by netbospl** [comment]
I'll have a look later on today and get back to you

**Comment by mozo78** [comment]
Thanks :)

**Comment by netbospl** [comment]
> Hello,
> Currently there's a problem compilng. It gives me:
> 
> https://pastebin.com/JPAuMiwS

I've fixed patch file, and updated PKGBUILD script.
Try now.

**Comment by mozo78** [comment]
Yes, it's working now. Thank you :)
