### ISSUE TITLE
Hunk #1 FAILED at 32.

### ISSUE THREAD

**Issue by mozo78** [netbospl/dolphin-git#2]
Hello,
When one try to compile, there's the following error:
`Cloning into 'dolphin'...
done.
==> Starting prepare()...
patching file src/main.cpp
Hunk #1 FAILED at 32.
1 out of 1 hunk FAILED -- saving rejects to file src/main.cpp.rej
==> ERROR: A failure occurred in prepare().
    Aborting...`

It seems the patch isn't compatible with the Dolphin latest version.

**Comment by netbospl** [comment]
I'll get around to fix it in 24h ish, To be completely honest I do not recommend using it, I've created this repo initially just for my one off case, even tho I'm maintaining it, I recommend replacing this build as soon as dolphin running as root is no longer required.

**Comment by mozo78** [comment]
The AUR package doesn't work either. I'm completely ok to use your PKGBUILD and patch and will wait for the fix, thanks :)

**Comment by netbospl** [comment]
Cool. I've fixed patch so it should work, try now.

**Comment by mozo78** [comment]
Yes it's working fine now. Thank you very much!
